version: "3.6"
services:

  gateway:
    build:
      context: ./gateway/
    ports:
      - 8080:8080
    links:
      - discounts
  discounts:
    build:
      context: ./discount/
    ports:
      - 8081:8080
